-- SCIEM — Script de creación de la base de datos
-- Versión 4 (public). Cambios respecto de V3:
--   * Esquema `modelinicial` reemplazado por `public`.
--   * PKs surrogate con GENERATED BY DEFAULT AS IDENTITY.
--   * public.usuario.id_usuario con DEFAULT gen_random_uuid().
--   * Extensión pgcrypto habilitada (requerida por gen_random_uuid).

CREATE SCHEMA IF NOT EXISTS public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

---------------------------------------------------
-- ENUMS
---------------------------------------------------

CREATE TYPE public.estado_registro AS ENUM (
    'ACTIVO',
    'INACTIVO'
);

CREATE TYPE public.estado_habilitacion AS ENUM (
    'HABILITADO',
	'CASO ESPECIAL',
    'NO_HABILITADO'
);

CREATE TYPE public.estado_ingreso AS ENUM (
    'INGRESO',
    'CON_RETRASO',
    'NO_INGRESO'
);

CREATE TYPE public.estado_invitacion AS ENUM (
    'PENDIENTE',
    'ACEPTADA',
    'RECHAZADA'
);

CREATE TYPE public.estado_reporte AS ENUM (
    'PENDIENTE',
    'APROBADO',
	'RECHAZADO'
);

CREATE TYPE public.categoria_examen AS ENUM (
    'REGULAR',
    'MESA',
	'ADMISION'
);

-- Ciclo de vida del examen (HU-24). Solo PROGRAMADO y CANCELADO se alcanzan hoy;
-- EN_INGRESO, EN_CURSO y FINALIZADO los asignan las historias de control de ingreso.
CREATE TYPE public.estado_examen AS ENUM (
    'PROGRAMADO',
    'EN_INGRESO',
    'EN_CURSO',
    'FINALIZADO',
    'CANCELADO'
);

---------------------------------------------------
-- accion
---------------------------------------------------

CREATE TABLE public.accion (
    id_accion       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operacion       varchar(100) NOT NULL,
    tipo_operacion  varchar(10) NOT NULL,
    descripcion     text,

    CONSTRAINT pk_accion
        PRIMARY KEY (id_accion)
);

---------------------------------------------------
-- ambiente
---------------------------------------------------

CREATE TABLE public.ambiente (
    id_ambiente     integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nro_aula        varchar(10) NOT NULL,
    capacidad       integer NOT NULL,
    ubicacion       text,
    estado          public.estado_registro NOT NULL,

    CONSTRAINT pk_ambiente
        PRIMARY KEY (id_ambiente),

    CONSTRAINT chk_ambiente_capacidad
        CHECK (capacidad > 0),
	
	CONSTRAINT unq_ambiente_nro_aula
    UNIQUE (nro_aula)
);

---------------------------------------------------
-- estudiante
---------------------------------------------------

CREATE TABLE public.estudiante (
    id_estudiante        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cod_sis              varchar(15) NOT NULL,
    -- NULL hasta la primera verificación (EX04): la nómina no trae el CI.
    ci                   varchar(10),
    nombre               varchar(50) NOT NULL,
    apellido_paterno     varchar(30) NOT NULL,
    apellido_materno     varchar(30),
    correo_institucional varchar(100),
    telefono             varchar(8),
    estado               public.estado_registro NOT NULL,

    CONSTRAINT pk_estudiante
        PRIMARY KEY (id_estudiante),

    CONSTRAINT unq_estudiante_cod_sis
        UNIQUE (cod_sis),

    CONSTRAINT unq_estudiante_ci
        UNIQUE (ci)
);

---------------------------------------------------
-- facultad
---------------------------------------------------

CREATE TABLE public.facultad (
    id_facultad  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       varchar(50) NOT NULL,
    codigo       varchar(50) NOT NULL,
    descripcion  text,
    estado       public.estado_registro
                 DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_facultad
        PRIMARY KEY (id_facultad),

    CONSTRAINT unq_facultad_codigo
        UNIQUE (codigo)
);

---------------------------------------------------
-- materia
---------------------------------------------------

CREATE TABLE public.materia (
    id_materia   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       varchar(50) NOT NULL,
    codigo       varchar(50) NOT NULL,
    descripcion  text,
    estado       public.estado_registro
                 DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_materia
        PRIMARY KEY (id_materia),

    CONSTRAINT unq_materia_codigo
        UNIQUE (codigo)
);

---------------------------------------------------
-- periodo
---------------------------------------------------

CREATE TABLE public.periodo (
    id_periodo      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_periodo  varchar(10) NOT NULL,
	gestion			smallint    NOT NULL,

    CONSTRAINT pk_periodo
        PRIMARY KEY (id_periodo),

    CONSTRAINT unq_periodo_nombre
        UNIQUE (nombre_periodo),

    CONSTRAINT chk_periodo_gestion
        CHECK (gestion BETWEEN 1900 AND 2200)
);

---------------------------------------------------
-- permiso
---------------------------------------------------

CREATE TABLE public.permiso (
    id_permiso      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_permiso  varchar(80) NOT NULL,
    descripcion     text,
    estado          public.estado_registro
                    DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_permiso
        PRIMARY KEY (id_permiso),

    CONSTRAINT unq_permiso_nombre
        UNIQUE (nombre_permiso)
);

---------------------------------------------------
-- postulante
---------------------------------------------------

CREATE TABLE public.postulante (
    id_postulante    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ci               varchar(10) NOT NULL,
    nombres          varchar(50) NOT NULL,
    apellido_paterno varchar(30) NOT NULL,
    apellido_materno varchar(30),
    correo           varchar(100),
    telefono         varchar(8),
    estado           public.estado_registro NOT NULL,

    CONSTRAINT pk_postulante
        PRIMARY KEY (id_postulante),

    CONSTRAINT unq_postulante_ci
        UNIQUE (ci)
);

---------------------------------------------------
-- rol
---------------------------------------------------

CREATE TABLE public.rol (
    id_rol          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_rol      varchar(20) NOT NULL,
    descripcion     text,
    fecha_registro  timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado          public.estado_registro
                    DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_rol
        PRIMARY KEY (id_rol),

    CONSTRAINT unq_rol_nombre
        UNIQUE (nombre_rol)
);

---------------------------------------------------
-- tipo_examen
---------------------------------------------------

CREATE TABLE public.tipo_examen (
    id_tipo_examen integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre         varchar(20) NOT NULL,
    categoria      public.categoria_examen NOT NULL,

    CONSTRAINT pk_tipo_examen
        PRIMARY KEY (id_tipo_examen),

    CONSTRAINT unq_tipo_examen_nombre
        UNIQUE (nombre)
);

---------------------------------------------------
-- tipo_falta
---------------------------------------------------

CREATE TABLE public.tipo_falta (
    id_falta      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre        varchar(30) NOT NULL,
    descripcion   text,

    CONSTRAINT pk_tipo_falta
        PRIMARY KEY (id_falta),

    CONSTRAINT unq_tipo_falta_nombre
        UNIQUE (nombre)
);

---------------------------------------------------
-- ui
---------------------------------------------------

CREATE TABLE public.ui (
    id_ui        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_ui    varchar(100) NOT NULL,
    descripcion  text,
    estado       public.estado_registro
                 DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_ui
        PRIMARY KEY (id_ui),

    CONSTRAINT unq_ui_nombre
        UNIQUE (nombre_ui)
);

---------------------------------------------------
-- ui_permiso
---------------------------------------------------

CREATE TABLE public.ui_permiso (
    id_ui       integer NOT NULL,
    id_permiso  integer NOT NULL,
    estado      public.estado_registro NOT NULL,

    CONSTRAINT pk_ui_permiso
        PRIMARY KEY (id_ui, id_permiso),

    CONSTRAINT fk_ui_permiso_ui
        FOREIGN KEY (id_ui)
        REFERENCES public.ui(id_ui),

    CONSTRAINT fk_ui_permiso_permiso
        FOREIGN KEY (id_permiso)
        REFERENCES public.permiso(id_permiso)
);

---------------------------------------------------
-- usuario
---------------------------------------------------

CREATE TABLE public.usuario (
    id_usuario        uuid DEFAULT gen_random_uuid() NOT NULL,
    nombre            varchar(50) NOT NULL,
    apellido_paterno  varchar(30) NOT NULL,
    apellido_materno  varchar(30),
    correo            varchar(100) NOT NULL,
    contrasenia       varchar(256) NOT NULL,
    cod_sis           varchar(15) NOT NULL,
    estado            public.estado_registro NOT NULL,

    CONSTRAINT pk_usuario
        PRIMARY KEY (id_usuario),

    CONSTRAINT unq_usuario_cod_sis
        UNIQUE (cod_sis),

    CONSTRAINT unq_usuario_correo
        UNIQUE (correo)
);

COMMENT ON TABLE public.usuario IS
'Para la sesión de los usuarios; tipos: Admin, docente y auxiliar';

---------------------------------------------------
-- usuario_rol
---------------------------------------------------

CREATE TABLE public.usuario_rol (
    id_usuario    uuid NOT NULL,
    id_rol        integer NOT NULL,
    fecha_inicio  timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_fin     timestamptz,

    CONSTRAINT pk_usuario_rol
        PRIMARY KEY (id_usuario, id_rol, fecha_inicio),

    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_usuario_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES public.rol(id_rol),

    CONSTRAINT chk_usuario_rol_fechas
        CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

---------------------------------------------------
-- log
---------------------------------------------------

CREATE TABLE public.log (
    id_log          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_accion       integer,
    antiguo_valor   jsonb,
    nuevo_valor     jsonb,
    fecha_hora      timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tabla_afectada  varchar NOT NULL,
    id_usuario 		uuid NOT NULL,

    CONSTRAINT pk_log
        PRIMARY KEY (id_log),

    CONSTRAINT fk_log_accion
        FOREIGN KEY (id_accion)
        REFERENCES public.accion(id_accion),
		
	CONSTRAINT fk_log_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario)
);

---------------------------------------------------
-- carrera
---------------------------------------------------

CREATE TABLE public.carrera (
    id_carrera   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       varchar(50) NOT NULL,
    codigo       varchar(50) NOT NULL,
    descripcion  text,
    estado       public.estado_registro
                 DEFAULT 'ACTIVO' NOT NULL,
    id_facultad  integer NOT NULL,

    CONSTRAINT pk_carrera
        PRIMARY KEY (id_carrera),

    CONSTRAINT unq_carrera_codigo
        UNIQUE (codigo),

    CONSTRAINT fk_carrera_facultad
        FOREIGN KEY (id_facultad)
        REFERENCES public.facultad(id_facultad)
);

---------------------------------------------------
-- convocatoria_admision
---------------------------------------------------

CREATE TABLE public.convocatoria_admision (
    id_admision   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_facultad   integer NOT NULL,
    id_periodo    integer NOT NULL,
    gestion       varchar(10) NOT NULL,
    nro_opciones  varchar(2) NOT NULL,
    estado        public.estado_registro NOT NULL,

    CONSTRAINT pk_convocatoria_admision
        PRIMARY KEY (id_admision),

    CONSTRAINT fk_convocatoria_admision_facultad
        FOREIGN KEY (id_facultad)
        REFERENCES public.facultad(id_facultad),

    CONSTRAINT fk_convocatoria_admision_periodo
        FOREIGN KEY (id_periodo)
        REFERENCES public.periodo(id_periodo)
);

---------------------------------------------------
-- examen
---------------------------------------------------

CREATE TABLE public.examen (
    id_examen       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_examen   varchar(25) NOT NULL,
    fecha           date NOT NULL,
    hora_inicio     time NOT NULL,
    hora_fin        time,
    duracion        integer,
    normas          text,
    id_tipo_examen  integer NOT NULL,
    id_carrera          integer,
    id_materia          integer,
    id_usuario_docente  uuid NOT NULL,
    estado              public.estado_examen
                        DEFAULT 'PROGRAMADO' NOT NULL,

    CONSTRAINT pk_examen
        PRIMARY KEY (id_examen),

    CONSTRAINT fk_examen_tipo_examen
        FOREIGN KEY (id_tipo_examen)
        REFERENCES public.tipo_examen(id_tipo_examen),

    CONSTRAINT fk_examen_usuario_docente
        FOREIGN KEY (id_usuario_docente)
        REFERENCES public.usuario(id_usuario),

    -- fk_examen_materia_carrera se declara después de crear materia_carrera.

    -- El par materia-carrera va completo o no va: un examen de admisión no tiene materia.
    CONSTRAINT chk_examen_materia_carrera
        CHECK ((id_carrera IS NULL) = (id_materia IS NULL)),

    -- hora_fin se deriva de la duración. Un examen que cruza la medianoche termina
    -- con una hora menor a la de inicio, por eso no se exige hora_fin > hora_inicio.
    CONSTRAINT chk_examen_hora_fin
        CHECK (
            hora_fin IS NULL
            OR duracion IS NULL
            OR hora_fin = hora_inicio + make_interval(mins => duracion)
        ),

    -- Menos de un día: la hora de fin no puede dar la vuelta completa al reloj.
    CONSTRAINT chk_examen_duracion
        CHECK (duracion IS NULL OR (duracion > 0 AND duracion < 1440))
);

---------------------------------------------------
-- examen_admision
---------------------------------------------------

CREATE TABLE public.examen_admision (
    id_admision  integer NOT NULL,
    id_examen    integer NOT NULL,
    nro_opcion   varchar(2) NOT NULL,

    CONSTRAINT pk_examen_admision
        PRIMARY KEY (id_admision, id_examen),

    CONSTRAINT unq_examen_admision_id_examen
        UNIQUE (id_examen),

    CONSTRAINT unq_examen_admision_nro_opcion
        UNIQUE (id_admision, nro_opcion),

    CONSTRAINT fk_examen_admision_convocatoria_admision
        FOREIGN KEY (id_admision)
        REFERENCES public.convocatoria_admision(id_admision),

    CONSTRAINT fk_examen_admision_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen)
);

---------------------------------------------------
-- examen_ambiente
---------------------------------------------------

CREATE TABLE public.examen_ambiente (
    id_examen    integer NOT NULL,
    id_ambiente  integer NOT NULL,

    CONSTRAINT pk_examen_ambiente
        PRIMARY KEY (id_examen, id_ambiente),

    CONSTRAINT fk_examen_ambiente_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen),

    CONSTRAINT fk_examen_ambiente_ambiente
        FOREIGN KEY (id_ambiente)
        REFERENCES public.ambiente(id_ambiente)
);

---------------------------------------------------
-- examen_postulante
---------------------------------------------------

CREATE TABLE public.examen_postulante (
    id_examen           integer NOT NULL,
    id_postulante       integer NOT NULL,
    estado_habilitacion public.estado_habilitacion NOT NULL,
    estado_ingreso      public.estado_ingreso NOT NULL,
    hora_ingreso        time,

    CONSTRAINT pk_examen_postulante
        PRIMARY KEY (id_examen, id_postulante),

    CONSTRAINT fk_examen_postulante_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen),

    CONSTRAINT fk_examen_postulante_postulante
        FOREIGN KEY (id_postulante)
        REFERENCES public.postulante(id_postulante),

    CONSTRAINT chk_examen_postulante_hora_ingreso
    CHECK (
        (
            estado_ingreso IN ('INGRESO', 'CON_RETRASO')
            AND hora_ingreso IS NOT NULL
        )
        OR
        (
            estado_ingreso = 'NO_INGRESO'
            AND hora_ingreso IS NULL
        )
    )
);

---------------------------------------------------
-- invitacion_examen
---------------------------------------------------

CREATE TABLE public.invitacion_examen (
    id_invitacion        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_examen             integer NOT NULL,
    id_docente_creador    uuid NOT NULL,
    id_docente_invitado   uuid NOT NULL,
    fecha_invitacion      timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_respuesta       timestamptz,
    estado                public.estado_invitacion NOT NULL,

    CONSTRAINT pk_invitacion_examen
        PRIMARY KEY (id_invitacion),

    CONSTRAINT fk_invitacion_examen_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen),

    CONSTRAINT fk_invitacion_examen_docente_creador
        FOREIGN KEY (id_docente_creador)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_invitacion_examen_docente_invitado
        FOREIGN KEY (id_docente_invitado)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT chk_invitacion_examen_fechas
        CHECK (
            fecha_respuesta IS NULL
            OR fecha_respuesta >= fecha_invitacion
        ),

    CONSTRAINT chk_invitacion_examen_estado
        CHECK (
            (estado = 'PENDIENTE' AND fecha_respuesta IS NULL)
            OR
            (estado IN ('ACEPTADA', 'RECHAZADA') AND fecha_respuesta IS NOT NULL)
        )
);

---------------------------------------------------
-- materia_carrera
---------------------------------------------------

CREATE TABLE public.materia_carrera (
    id_carrera      integer NOT NULL,
    id_materia      integer NOT NULL,
    nivel_semestre  varchar(15),
    obligatoria     boolean,
    estado          public.estado_registro
                    DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_materia_carrera
        PRIMARY KEY (id_carrera, id_materia),

    CONSTRAINT fk_materia_carrera_carrera
        FOREIGN KEY (id_carrera)
        REFERENCES public.carrera(id_carrera),

    CONSTRAINT fk_materia_carrera_materia
        FOREIGN KEY (id_materia)
        REFERENCES public.materia(id_materia)
);

-- examen se crea antes que materia_carrera: su clave compuesta hacia el par se agrega aquí,
-- igual que la de grupo.
ALTER TABLE public.examen
    ADD CONSTRAINT fk_examen_materia_carrera
        FOREIGN KEY (id_carrera, id_materia)
        REFERENCES public.materia_carrera(id_carrera, id_materia);

---------------------------------------------------
-- permiso_rol
---------------------------------------------------

CREATE TABLE public.permiso_rol (
    id_permiso  integer NOT NULL,
    id_rol      integer NOT NULL,
    estado      public.estado_registro NOT NULL,

    CONSTRAINT pk_permiso_rol
        PRIMARY KEY (id_permiso, id_rol),

    CONSTRAINT fk_permiso_rol_permiso
        FOREIGN KEY (id_permiso)
        REFERENCES public.permiso(id_permiso),

    CONSTRAINT fk_permiso_rol_rol
        FOREIGN KEY (id_rol)
        REFERENCES public.rol(id_rol)
);

---------------------------------------------------
-- reporte_estudiante
---------------------------------------------------

CREATE TABLE public.reporte_estudiante (
    id_reporte_est        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_estudiante         integer NOT NULL,
    id_examen             integer NOT NULL,
    id_tipo_falta         integer NOT NULL,
    id_usuario_reportante uuid NOT NULL,
    descripcion           text,
    evidencia_url         text NOT NULL,
    evidencia_public_id   varchar NOT NULL,
    fecha_reporte         timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado                public.estado_reporte NOT NULL,
    fecha_revision       timestamptz,
    observacion_revision  text,
    id_usuario_revisor    uuid,

    CONSTRAINT pk_reporte_estudiante
        PRIMARY KEY (id_reporte_est),

    CONSTRAINT fk_reporte_estudiante_tipo_falta
        FOREIGN KEY (id_tipo_falta)
        REFERENCES public.tipo_falta(id_falta),

    CONSTRAINT fk_reporte_estudiante_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES public.estudiante(id_estudiante),

    CONSTRAINT fk_reporte_estudiante_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen),

    CONSTRAINT fk_reporte_estudiante_usuario_reportante
        FOREIGN KEY (id_usuario_reportante)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_reporte_estudiante_usuario_revisor
        FOREIGN KEY (id_usuario_revisor)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT chk_reporte_estudiante_revision
    CHECK (
        (
            estado = 'PENDIENTE'
            AND fecha_revision IS NULL
            AND id_usuario_revisor IS NULL
        )
        OR
        (
            estado IN ('APROBADO', 'RECHAZADO')
            AND fecha_revision IS NOT NULL
            AND id_usuario_revisor IS NOT NULL
        )
    )
);

---------------------------------------------------
-- reporte_postulante
---------------------------------------------------

CREATE TABLE public.reporte_postulante (
    id_reporte_post       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_postulante         integer NOT NULL,
    id_examen             integer NOT NULL,
    id_tipo_falta         integer NOT NULL,
    id_usuario_reportante uuid NOT NULL,
    descripcion           text,
    evidencia_url         text NOT NULL,
    evidencia_public_id   varchar NOT NULL,
    fecha_reporte         timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado                public.estado_reporte NOT NULL,
    fecha_revision        timestamptz,
    observacion_revision  text,
    id_usuario_revisor    uuid,

    CONSTRAINT pk_reporte_postulante
        PRIMARY KEY (id_reporte_post),

    CONSTRAINT fk_reporte_postulante_tipo_falta
        FOREIGN KEY (id_tipo_falta)
        REFERENCES public.tipo_falta(id_falta),

    CONSTRAINT fk_reporte_postulante_postulante
        FOREIGN KEY (id_postulante)
        REFERENCES public.postulante(id_postulante),

    CONSTRAINT fk_reporte_postulante_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen),

    CONSTRAINT fk_reporte_postulante_usuario_reportante
        FOREIGN KEY (id_usuario_reportante)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_reporte_postulante_usuario_revisor
        FOREIGN KEY (id_usuario_revisor)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT chk_reporte_postulante_revision
    CHECK (
        (
            estado = 'PENDIENTE'
            AND fecha_revision IS NULL
            AND id_usuario_revisor IS NULL
        )
        OR
        (
            estado IN ('APROBADO', 'RECHAZADO')
            AND fecha_revision IS NOT NULL
            AND id_usuario_revisor IS NOT NULL
        )
    )
);

---------------------------------------------------
-- sesion
---------------------------------------------------

CREATE TABLE public.sesion (
    id_sesion      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario     uuid NOT NULL,
    pid            integer NOT NULL,
    ip_direccion   inet NOT NULL,
    num_puerto     integer NOT NULL,
    hora_ingreso   timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sesion
        PRIMARY KEY (id_sesion, id_usuario),

    CONSTRAINT fk_sesion_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario)
);

---------------------------------------------------
-- central_riesgo
---------------------------------------------------

CREATE TABLE public.central_riesgo (
    id_cr_estudiante  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_reporte_est    integer NOT NULL,
    id_estudiante     integer NOT NULL,
    fecha_registro    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_central_riesgo
        PRIMARY KEY (id_cr_estudiante),

    CONSTRAINT unq_central_riesgo_id_reporte
        UNIQUE (id_reporte_est),

    CONSTRAINT fk_central_riesgo_reporte_estudiante
        FOREIGN KEY (id_reporte_est)
        REFERENCES public.reporte_estudiante(id_reporte_est),

    CONSTRAINT fk_central_riesgo_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES public.estudiante(id_estudiante)
);

---------------------------------------------------
-- central_riesgo_postulante
---------------------------------------------------

CREATE TABLE public.central_riesgo_postulante (
    id_cr_postulante  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_reporte_post   integer NOT NULL,
    id_postulante     integer NOT NULL,
    fecha_registro    timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_central_riesgo_postulante
        PRIMARY KEY (id_cr_postulante),

    CONSTRAINT unq_central_riesgo_postulante_id_reporte
        UNIQUE (id_reporte_post),

    CONSTRAINT fk_central_riesgo_postulante_reporte
        FOREIGN KEY (id_reporte_post)
        REFERENCES public.reporte_postulante(id_reporte_post),

    CONSTRAINT fk_central_riesgo_postulante_postulante
        FOREIGN KEY (id_postulante)
        REFERENCES public.postulante(id_postulante)
);

---------------------------------------------------
-- grupo
---------------------------------------------------

CREATE TABLE public.grupo (
    id_grupo            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_carrera          integer NOT NULL,
    id_materia          integer NOT NULL,
    num_grupo           varchar (5) NOT NULL,
    gestion             varchar(10) NOT NULL,
    estado              public.estado_registro
                        DEFAULT 'ACTIVO' NOT NULL,
    id_usuario_docente  uuid NOT NULL,
    id_periodo          integer NOT NULL,

    CONSTRAINT pk_grupo
        PRIMARY KEY (id_grupo),

    CONSTRAINT fk_grupo_materia_carrera
        FOREIGN KEY (id_carrera, id_materia)
        REFERENCES public.materia_carrera(id_carrera, id_materia),

    CONSTRAINT fk_grupo_usuario_docente
        FOREIGN KEY (id_usuario_docente)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fk_grupo_periodo
        FOREIGN KEY (id_periodo)
        REFERENCES public.periodo(id_periodo),
		
	CONSTRAINT unq_grupo
    UNIQUE (
        id_carrera,
        id_materia,
        num_grupo,
        gestion,
        id_periodo
    )
);

---------------------------------------------------
-- grupo_estudiante
---------------------------------------------------

CREATE TABLE public.grupo_estudiante (
    id_grupo          integer NOT NULL,
    id_estudiante     integer NOT NULL,
    fecha_inscripcion date NOT NULL,
    estado            public.estado_registro NOT NULL,

    CONSTRAINT pk_grupo_estudiante
        PRIMARY KEY (id_grupo, id_estudiante),

    CONSTRAINT fk_grupo_estudiante_grupo
        FOREIGN KEY (id_grupo)
        REFERENCES public.grupo(id_grupo),

    CONSTRAINT fk_grupo_estudiante_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES public.estudiante(id_estudiante)
);

---------------------------------------------------
-- grupo_examen
---------------------------------------------------

CREATE TABLE public.grupo_examen (
    id_grupo   integer NOT NULL,
    id_examen  integer NOT NULL,

    CONSTRAINT pk_grupo_examen
        PRIMARY KEY (id_grupo, id_examen),

    CONSTRAINT fk_grupo_examen_grupo
        FOREIGN KEY (id_grupo)
        REFERENCES public.grupo(id_grupo),

    CONSTRAINT fk_grupo_examen_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen)
);

---------------------------------------------------
-- examen_estudiante
---------------------------------------------------

CREATE TABLE public.examen_estudiante (
    id_examen            integer NOT NULL,
    id_estudiante        integer NOT NULL,
    estado_habilitacion  public.estado_habilitacion NOT NULL,
    observacion          text,
    estado_ingreso       public.estado_ingreso NOT NULL,
    hora_ingreso         time,
    id_grupo             integer NOT NULL,

    CONSTRAINT pk_examen_estudiante
        PRIMARY KEY (id_examen, id_estudiante),

    CONSTRAINT fk_examen_estudiante_examen
        FOREIGN KEY (id_examen)
        REFERENCES public.examen(id_examen),

    CONSTRAINT fk_examen_estudiante_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES public.estudiante(id_estudiante),
		
	CONSTRAINT fk_examen_estudiante_grupo_examen
    	FOREIGN KEY (id_grupo, id_examen)
    	REFERENCES public.grupo_examen(id_grupo, id_examen),

	CONSTRAINT fk_examen_estudiante_grupo_estudiante
	    FOREIGN KEY (id_grupo, id_estudiante)
	    REFERENCES public.grupo_estudiante(id_grupo, id_estudiante),

    CONSTRAINT chk_examen_estudiante_hora_ingreso
    CHECK (
        (
            estado_ingreso IN ('INGRESO', 'CON_RETRASO')
            AND hora_ingreso IS NOT NULL
        )
        OR
        (
            estado_ingreso = 'NO_INGRESO'
            AND hora_ingreso IS NULL
        )
    )
);

---------------------------------------------------
-- ÍNDICES
---------------------------------------------------

-- ACCION
CREATE INDEX idx_accion_tipo_operacion
    ON public.accion(tipo_operacion);

---------------------------------------------------
-- AMBIENTE
CREATE INDEX idx_ambiente_estado
    ON public.ambiente(estado);

CREATE INDEX idx_ambiente_nro_aula
    ON public.ambiente(nro_aula);

---------------------------------------------------
-- ESTUDIANTE
---------------------------------------------------
-- cod_sis y ci ya tienen índices por UNIQUE.

CREATE INDEX idx_estudiante_estado
    ON public.estudiante(estado);

CREATE INDEX idx_estudiante_nombre
    ON public.estudiante(apellido_paterno, apellido_materno, nombre);

---------------------------------------------------
-- FACULTAD
---------------------------------------------------
-- codigo ya tiene índice por UNIQUE.

CREATE INDEX idx_facultad_estado
    ON public.facultad(estado);

---------------------------------------------------
-- LOG
---------------------------------------------------

CREATE INDEX idx_log_accion
    ON public.log(id_accion);

CREATE INDEX idx_log_fecha_hora
    ON public.log(fecha_hora);

CREATE INDEX idx_log_tabla_afectada
    ON public.log(tabla_afectada);

CREATE INDEX idx_log_usuario
    ON public.log(id_usuario);

---------------------------------------------------
-- MATERIA
---------------------------------------------------

CREATE INDEX idx_materia_estado
    ON public.materia(estado);

---------------------------------------------------
-- PERMISO
---------------------------------------------------

CREATE INDEX idx_permiso_estado
    ON public.permiso(estado);

---------------------------------------------------
-- POSTULANTE
---------------------------------------------------

CREATE INDEX idx_postulante_estado
    ON public.postulante(estado);

CREATE INDEX idx_postulante_nombre
    ON public.postulante(apellido_paterno, apellido_materno, nombres);

---------------------------------------------------
-- ROL
---------------------------------------------------

CREATE INDEX idx_rol_estado
    ON public.rol(estado);

---------------------------------------------------
-- TIPO EXAMEN
---------------------------------------------------

CREATE INDEX idx_tipo_examen_categoria
    ON public.tipo_examen(categoria);

---------------------------------------------------
-- TIPO FALTA
---------------------------------------------------

---------------------------------------------------
-- UI
---------------------------------------------------

CREATE INDEX idx_ui_estado
    ON public.ui(estado);

---------------------------------------------------
-- UI PERMISO
---------------------------------------------------

-- La PK ya cubre búsquedas por id_ui.
CREATE INDEX idx_ui_permiso_permiso
    ON public.ui_permiso(id_permiso);

CREATE INDEX idx_ui_permiso_estado
    ON public.ui_permiso(estado);

---------------------------------------------------
-- USUARIO
---------------------------------------------------

CREATE INDEX idx_usuario_estado
    ON public.usuario(estado);

---------------------------------------------------
-- USUARIO ROL
---------------------------------------------------

-- La PK empieza por id_usuario.
CREATE INDEX idx_usuario_rol_rol
    ON public.usuario_rol(id_rol);

CREATE INDEX idx_usuario_rol_fecha_fin
    ON public.usuario_rol(fecha_fin);

---------------------------------------------------
-- CARRERA
---------------------------------------------------

CREATE INDEX idx_carrera_facultad
    ON public.carrera(id_facultad);

CREATE INDEX idx_carrera_estado
    ON public.carrera(estado);

---------------------------------------------------
-- CONVOCATORIA ADMISION
---------------------------------------------------

CREATE INDEX idx_convocatoria_admision_facultad
    ON public.convocatoria_admision(id_facultad);

CREATE INDEX idx_convocatoria_admision_periodo
    ON public.convocatoria_admision(id_periodo);

CREATE INDEX idx_convocatoria_admision_gestion
    ON public.convocatoria_admision(gestion);

CREATE INDEX idx_convocatoria_admision_estado
    ON public.convocatoria_admision(estado);

---------------------------------------------------
-- EXAMEN
---------------------------------------------------

CREATE INDEX idx_examen_tipo
    ON public.examen(id_tipo_examen);

CREATE INDEX idx_examen_fecha
    ON public.examen(fecha);

CREATE INDEX idx_examen_fecha_hora
    ON public.examen(fecha, hora_inicio);

CREATE INDEX idx_examen_materia_carrera
    ON public.examen(id_carrera, id_materia);

CREATE INDEX idx_examen_usuario_docente
    ON public.examen(id_usuario_docente, fecha);

CREATE INDEX idx_examen_estado
    ON public.examen(estado);

---------------------------------------------------
-- EXAMEN ADMISION
---------------------------------------------------

-- La PK cubre id_admision.
-- id_examen ya tiene índice por UNIQUE.

---------------------------------------------------
-- EXAMEN AMBIENTE
---------------------------------------------------

-- La PK cubre búsquedas por id_examen.
CREATE INDEX idx_examen_ambiente_ambiente
    ON public.examen_ambiente(id_ambiente);

---------------------------------------------------
-- EXAMEN POSTULANTE
---------------------------------------------------

-- La PK cubre id_examen.
CREATE INDEX idx_examen_postulante_postulante
    ON public.examen_postulante(id_postulante);

CREATE INDEX idx_examen_postulante_habilitacion
    ON public.examen_postulante(estado_habilitacion);

CREATE INDEX idx_examen_postulante_ingreso
    ON public.examen_postulante(estado_ingreso);
	
CREATE INDEX idx_examen_postulante_examen_estado_ingreso
    ON public.examen_postulante(
        id_examen,
        estado_ingreso
    );

CREATE INDEX idx_examen_postulante_examen_habilitacion
    ON public.examen_postulante(
        id_examen,
        estado_habilitacion
    );

---------------------------------------------------
-- INVITACION EXAMEN
---------------------------------------------------

CREATE INDEX idx_invitacion_examen_examen
    ON public.invitacion_examen(id_examen);

CREATE INDEX idx_invitacion_examen_creador
    ON public.invitacion_examen(id_docente_creador);

CREATE INDEX idx_invitacion_examen_invitado
    ON public.invitacion_examen(id_docente_invitado);

CREATE INDEX idx_invitacion_examen_estado
    ON public.invitacion_examen(estado);

CREATE INDEX idx_invitacion_examen_fecha
    ON public.invitacion_examen(fecha_invitacion);

---------------------------------------------------
-- MATERIA CARRERA
---------------------------------------------------

-- La PK cubre id_carrera.
CREATE INDEX idx_materia_carrera_materia
    ON public.materia_carrera(id_materia);

CREATE INDEX idx_materia_carrera_estado
    ON public.materia_carrera(estado);

---------------------------------------------------
-- PERMISO ROL
---------------------------------------------------

-- La PK cubre id_permiso.
CREATE INDEX idx_permiso_rol_rol
    ON public.permiso_rol(id_rol);

CREATE INDEX idx_permiso_rol_estado
    ON public.permiso_rol(estado);

---------------------------------------------------
-- REPORTE ESTUDIANTE
---------------------------------------------------

CREATE INDEX idx_reporte_estudiante_estudiante
    ON public.reporte_estudiante(id_estudiante);

CREATE INDEX idx_reporte_estudiante_examen
    ON public.reporte_estudiante(id_examen);

CREATE INDEX idx_reporte_estudiante_tipo_falta
    ON public.reporte_estudiante(id_tipo_falta);

CREATE INDEX idx_reporte_estudiante_reportante
    ON public.reporte_estudiante(id_usuario_reportante);

CREATE INDEX idx_reporte_estudiante_revisor
    ON public.reporte_estudiante(id_usuario_revisor);

CREATE INDEX idx_reporte_estudiante_estado
    ON public.reporte_estudiante(estado);

CREATE INDEX idx_reporte_estudiante_fecha
    ON public.reporte_estudiante(fecha_reporte);

---------------------------------------------------
-- REPORTE POSTULANTE
---------------------------------------------------

CREATE INDEX idx_reporte_postulante_postulante
    ON public.reporte_postulante(id_postulante);

CREATE INDEX idx_reporte_postulante_examen
    ON public.reporte_postulante(id_examen);

CREATE INDEX idx_reporte_postulante_tipo_falta
    ON public.reporte_postulante(id_tipo_falta);

CREATE INDEX idx_reporte_postulante_reportante
    ON public.reporte_postulante(id_usuario_reportante);

CREATE INDEX idx_reporte_postulante_revisor
    ON public.reporte_postulante(id_usuario_revisor);

CREATE INDEX idx_reporte_postulante_estado
    ON public.reporte_postulante(estado);

CREATE INDEX idx_reporte_postulante_fecha
    ON public.reporte_postulante(fecha_reporte);

---------------------------------------------------
-- SESION
---------------------------------------------------

CREATE INDEX idx_sesion_usuario
    ON public.sesion(id_usuario);

CREATE INDEX idx_sesion_hora_ingreso
    ON public.sesion(hora_ingreso);

---------------------------------------------------
-- CENTRAL RIESGO
---------------------------------------------------

CREATE INDEX idx_central_riesgo_estudiante
    ON public.central_riesgo(id_estudiante);

---------------------------------------------------
-- CENTRAL RIESGO POSTULANTE
---------------------------------------------------

CREATE INDEX idx_central_riesgo_postulante
    ON public.central_riesgo_postulante(id_postulante);

---------------------------------------------------
-- GRUPO
---------------------------------------------------

CREATE INDEX idx_grupo_carrera_materia
    ON public.grupo(id_carrera, id_materia);

CREATE INDEX idx_grupo_docente
    ON public.grupo(id_usuario_docente);

CREATE INDEX idx_grupo_periodo
    ON public.grupo(id_periodo);

CREATE INDEX idx_grupo_gestion
    ON public.grupo(gestion);

CREATE INDEX idx_grupo_estado
    ON public.grupo(estado);

---------------------------------------------------
-- GRUPO ESTUDIANTE
---------------------------------------------------

-- La PK cubre id_grupo.
CREATE INDEX idx_grupo_estudiante_estudiante
    ON public.grupo_estudiante(id_estudiante);

CREATE INDEX idx_grupo_estudiante_estado
    ON public.grupo_estudiante(estado);
	
CREATE INDEX idx_grupo_estudiante_grupo_estado
    ON public.grupo_estudiante(id_grupo, estado);


---------------------------------------------------
-- GRUPO EXAMEN
---------------------------------------------------

-- La PK cubre id_grupo.
CREATE INDEX idx_grupo_examen_examen
    ON public.grupo_examen(id_examen);

---------------------------------------------------
-- EXAMEN ESTUDIANTE
---------------------------------------------------

-- La PK cubre id_examen.
CREATE INDEX idx_examen_estudiante_estudiante
    ON public.examen_estudiante(id_estudiante);

CREATE INDEX idx_examen_estudiante_grupo
    ON public.examen_estudiante(id_grupo);

CREATE INDEX idx_examen_estudiante_habilitacion
    ON public.examen_estudiante(estado_habilitacion);

CREATE INDEX idx_examen_estudiante_ingreso
    ON public.examen_estudiante(estado_ingreso);
	
CREATE INDEX idx_examen_estudiante_examen_estado_ingreso
    ON public.examen_estudiante(
        id_examen,
        estado_ingreso
    );

CREATE INDEX idx_examen_estudiante_examen_habilitacion
    ON public.examen_estudiante(
        id_examen,
        estado_habilitacion
    );

